App:
  Name: go-template
  Port: 8080
  Timeout: 60s

Log:
  Level: "debug"
  Env: "dev"

Database:
  Host: localhost
  Port: 3306
  Database: test


Redis:
  Addr: localhost
  Port: 6379
  Expiration: 24h
  Db: 0
  PoolSize: 50


Secrets: 
  RedisPassword: ""
  DbUsername: root
  DbPassword: ""
